apiVersion: v1
kind: Service
metadata:
  name: rails-app
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.rails.servicePort }}
      targetPort: {{ .Values.rails.servicePort }}
  selector:
    app: rails-app
